#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-konstruktion =						\
	papers/konstruktion/packages.tex					\
	papers/konstruktion/main.tex					\
	papers/konstruktion/references.bib				\
	papers/konstruktion/teil0.tex					\
	papers/konstruktion/teil1.tex					\
	papers/konstruktion/teil2.tex					\
	papers/konstruktion/teil3.tex

