#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-abb =						\
	papers/abb/packages.tex					\
	papers/abb/main.tex					\
	papers/abb/references.bib				\
	papers/abb/teil0.tex					\
	papers/abb/teil1.tex					\
	papers/abb/teil2.tex					\
	papers/abb/teil3.tex

